# An Array generated by a simple literal
# preserves the order of the element types
tuple = ["John", 20]

# You can take each element
tuple[0] + "str" # No error
tuple[1] + 20    # No error

# If you call any method, the order is lost
ary = tuple.to_a
ary[0] + "str" # Error!


# Hash works great too
hash = { name: "John", age: 20 }

hash[:name] + "str"
hash[:age] + 1
